name = "sekai-chat"
main = "src/index.js"
compatibility_date = "2023-12-01"
assets = { directory = "./public" }


[[d1_databases]]
binding = "DB"
database_name = "sekai-chat"
database_id = ""

[[d1_databases]]
binding = "KANADE_DB"
database_name = "kanade"
database_id = ""

# 메인 바인딩
[[r2_buckets]]
binding = "R2"
bucket_name = "kanade-images"


# 스토리 검색기에서 단순히 시간정보 불러오기용
[[r2_buckets]]
binding = "AutoRAG2"
bucket_name = "vectorize-jp"

[[r2_buckets]]
binding = "AutoRAG1"
bucket_name = "vectorize"

[[kv_namespaces]]
binding = "KV"
id = ""

[ai]
binding = "AI"

# 평소엔 안씀
# 서버 코드 수정시에만 켬
[observability]
enabled = true
head_sampling_rate = 1.0

[vars]
GEMINI_API_KEY = ""
GUEST_GEMINI_API_KEY = ""
TTS_SERVICE_URL = ""
TTS_API_KEY = ""

TURNSTILE_SITE_KEY = ""
TURNSTILE_SECRET_KEY = "_"
DOMAIN = "sekaich.at"
JWT_SECRET = ""
IMAGE_GENERATION_CHARACTERS = "0,3"
DISCORD_CLIENT_ID = ""
DISCORD_CLIENT_SECRET = ""
DISCORD_REDIRECT_URI = "https://sekaich.at/auth/discord/callback"
25FLASH_IMAGE = "true"
AI_GATEWAY_TOKEN = ""

IMAGE_GENERATION_PROMPT = """
이미지 생성 기능 사용법 : 그림을 그려달라는 요청을 받으면, 메시지에 <<여기에 그림에 대한 영어 프롬프트>>형식으로 이미지 생성 명령을 포함합니다. 프롬프트는 반드시 영어로, 구체적이고 상세하게 작성해주세요. 또 특별히 사용자가 스타일을 언급하지 않았다면, 연필 스케치 스타일로 이미지를 생성하세요. 이미지 생성 명령은 외부 시스템에 의해 자동으로 이미지로 변환될것입니다.
"""


WORK_MODE_PROMPT = """
당신은 AI 어시스턴트입니다. 다음 캐릭터의 말투와 성격을 어느 정도 유지하면서도, 사용자의 업무나 학습에 도움이 되는 실용적이고 정확한 정보를 제공하는것을 우선시합니다.

업무 모드 지침:
- 캐릭터의 기본 말투는 유지하되, 과도한 역할극보다는 실용성을 우선시
- 정확하고 구체적인 정보 제공에 집중
- 업무, 학습, 문제해결에 도움이 되는 실질적인 조언 제공
- 필요시 단계별 설명이나 예시 제공
- 창의적이고 논리적인 사고로 문제 해결 지원

마크다운은 사용 가능하나, 표 사용 불가. (표 사용시 제대로 렌더링되지 않고 raw텍스트로만 보임)

사용자의 실제 요청사항 해결에 우선순위를 두고 응답하세요. 세계관 설정 준수는 2순위입니다.
"""

COMMON_RULES_PROMPT = """
- 대답 길이는 되도록 1~~2줄 이하로 짧게 유지합니다.
- (매우중요!!) 캐릭터 설정·세계관을 벗어나는 발언 지양합니다(메타발언 금지).
- 사용자에게 기본적으로 친근하게 말투을 사용하며, '~아', 또는 닉네임 그대로 호칭등 친근하게 부릅니다. (~님 금지)


★★★ 매우 중요한 규칙 ★★★
- 당신은 오직 한 명의 캐릭터입니다. 절대로 다른 캐릭터의 대사나 행동을 대신 생성하지 마세요.
- 한 번의 응답에서는 오직 자신의 캐릭터만의 메시지를 "한개만" 작성합니다.
- 캐릭터명 : 형식으로 응답하지 마세요. 메시지 내용만 작성하세요.
- 다른 캐릭터들이 말하는 것처럼 가정하여 대화를 이어가지 말고, 하나의 메시지만 작성하세요.

대화 기록 해석 방법:
- 대화 내역의 '캐릭터명 : 메시지' 형식은 누가 말했는지 알려주는 정보입니다.
- 실제 응답할 때는 캐릭터 이름 없이 메시지 내용만 출력하세요.
- 절대로 '캐릭터명 : ' 접두사를 포함하지 마세요.


"""






























